### ISSUE TITLE
Check the structure of stoa0149b.stoa002.opp-lat1.xml

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/csel-dev#252]
There appear to be \<div subtype="chunk"\> elements under the subtype="letter" divs.  Are these necessary?  Should we incorporate them into the citation scheme (they have @n attributes)?

**Comment by simonastoyanova** [comment]
No, they should be something else. Will investigate and correct when I get
to this issue. Thanks!

On 10 December 2015 at 12:44, sonofmun <notifications@github.com> wrote:

> There appear to be <div subtype="chunk"> elements under the
> subtype="letter" divs. Are these necessary? Should we incorporate them into
> the citation scheme (they have @n <https://github.com/n> attributes)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenGreekAndLatin/csel-dev/issues/252>.
>



-- 
Simona Stoyanova
Research Associate

Digital Humanities
Department of Computer Science
University of Leipzig
Augustusplatz 10
04109 Leipzig, Germany

**Comment by annettegessner** [comment]
This might be what (or similar to what) @pmsprenger had been working on. We might just get rid of one of these levels. I am looking onto it.

**Comment by annettegessner** [comment]
The Structure is horrific: Book, letter, chunk, chapter, section.
But not all the letters have chunks and/or sections and I don't think we can remove any of these levels, since they influence the numbering of the others. 
So - if I am not mistaken - to keep it consistent, we'd have to make sure, all the levels are everywhere, even if there are not many "chunks" (which we'd have to rename somehow)? I am so not happy with this. Anybody any idea?

**Comment by annettegessner** [comment]
If nobody objects, I would follow this pragmatic approach: I will name the levels in a specific way regardless of their content. So the first level is always book(1), the second letter(2), the third will always be chapter(3), the fourth section(4) and the fifth level (if even occurring) I will name passage(5). Objecitons, better ideas and a better name for the fifth level welcome!

**Comment by annettegessner** [comment]
Done - see PR #261 - passing hook test.
