### ISSUE TITLE
Missing Perseus Catalog URIs for works (CSEL12)

### ISSUE THREAD

**Issue by gfranzini** [OpenGreekAndLatin/csel-dev#7]

**Comment by sonofmun** [comment]
We still need these URNs @AlisonBabeu You can see the works in volume 12 on the spreadsheet here https://docs.google.com/spreadsheets/d/1D3Y5i5xENpckX7lahpdRAbSkpxL2Q_RQc3d5oMKluhQ/edit#gid=0, on lines 80-81.

**Comment by AlisonBabeu** [comment]
Unless I'm missing something I had put the URNs stoa0040.stoa080 and stoa0040.stoa080a for these two works of Augustine. It is what I had used in the catalog record, which is currently available in catalog_pending, https://github.com/PerseusDL/catalog_pending/blob/master/mods/Augustine/augustine.CSELVol12.mods.xml.

**Comment by sonofmun** [comment]
Ah, OK.  Yes, we have the work IDs but not the full edition URNs.  Do we get those from you, Alison?  Or is there another process to do that?

**Comment by AlisonBabeu** [comment]
I never officially assign edition URNs as the Perseus Catalog system creates them from the work IDs but in the case of these works I think since this is the first edition in question for both of these works by Augustine that the CTSURNs would simply be urn:cts:latinLit:stoa0040.stoa080.opp-lat1 and urn:cts:latinLit:stoa0040.stoa080a.opp-lat1.

urn:cts:latinLit:stoa0263b.stoa002

**Comment by sonofmun** [comment]
Thanks @AlisonBabeu I have changed it in our table and it should soon show up in the repository as well.
